version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gasu-web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=True
      - DB_ENGINE=sqlite
      - DJANGO_SETTINGS_MODULE=web.settings
    command: >
      sh -c "python manage.py migrate &&
             python manage.py create_demo &&
             python manage.py runserver 0.0.0.0:8000"
    stdin_open: true
    tty: true

